// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: books.sql

package tutorial

import (
	"context"
	"database/sql"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (
    name, author_id
) VALUES (
    ?, ?
)
RETURNING id, name, author_id
`

type CreateBookParams struct {
	Name     string
	AuthorID sql.NullInt64
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook, arg.Name, arg.AuthorID)
	var i Book
	err := row.Scan(&i.ID, &i.Name, &i.AuthorID)
	return i, err
}

const getBook = `-- name: GetBook :one
SELECT id, name, author_id FROM books
WHERE id = ? LIMIT 1
`

func (q *Queries) GetBook(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBook, id)
	var i Book
	err := row.Scan(&i.ID, &i.Name, &i.AuthorID)
	return i, err
}
